Compilation Error in model core__model_one_thousand_two_hundred_and_ninety (models/core_reporting_models/core__model_one_thousand_two_hundred_and_ninety.sql)
  Model 'model.xtra_large_project_simulation.core__model_one_thousand_two_hundred_and_ninety' (models/core_reporting_models/core__model_one_thousand_two_hundred_and_ninety.sql) depends on a node named 'stg__contacts' which was not found
