Compilation Error in model core__model_three_hundred_and_thirty_seven (models/core_reporting_models/core__model_three_hundred_and_thirty_seven.sql)
  Model 'model.xtra_large_project_simulation.core__model_three_hundred_and_thirty_seven' (models/core_reporting_models/core__model_three_hundred_and_thirty_seven.sql) depends on a node named 'stg__contacts' which was not found
